name: 'Jack Ruder'
profile_image: jack/profile_pictures/20251020_064804130_ios.jpg
email: jack@djl.foundation
location: 'Stade, Niedersachsen, Deuschland'
short_bio: |-
  Ich bin Jack,
  alles Wichtige muss ich hier noch schreiben
  Also [PLACEHOLDER]
github_url: 'https://github.com/JackatDJL'
codeberg_url: 'https://codeberg.org/jkxrx'
