/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as NowRouteImport } from './routes/now'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as WritingRouteImport } from './routes/writing'
import { Route as CvIndexRouteImport } from './routes/cv/index'
import { Route as CvProfileRouteImport } from './routes/cv/$profile'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as WritingSlugRouteImport } from './routes/writing.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const NowRoute = NowRouteImport.update({
  id: '/now',
  path: '/now',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingRoute = WritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const CvIndexRoute = CvIndexRouteImport.update({
  id: '/cv/',
  path: '/cv/',
  getParentRoute: () => rootRouteImport,
} as any)
const CvProfileRoute = CvProfileRouteImport.update({
  id: '/cv/$profile',
  path: '/cv/$profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const WritingSlugRoute = WritingSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WritingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/now': typeof NowRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/writing': typeof WritingRouteWithChildren
  '/cv/$profile': typeof CvProfileRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/cv/': typeof CvIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/now': typeof NowRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/writing': typeof WritingRouteWithChildren
  '/cv/$profile': typeof CvProfileRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/cv': typeof CvIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/now': typeof NowRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/writing': typeof WritingRouteWithChildren
  '/cv/$profile': typeof CvProfileRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/cv/': typeof CvIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/now'
    | '/projects'
    | '/writing'
    | '/cv/$profile'
    | '/projects/$slug'
    | '/writing/$slug'
    | '/cv/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/now'
    | '/projects'
    | '/writing'
    | '/cv/$profile'
    | '/projects/$slug'
    | '/writing/$slug'
    | '/cv'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/now'
    | '/projects'
    | '/writing'
    | '/cv/$profile'
    | '/projects/$slug'
    | '/writing/$slug'
    | '/cv/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  NowRoute: typeof NowRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  WritingRoute: typeof WritingRouteWithChildren
  CvProfileRoute: typeof CvProfileRoute
  CvIndexRoute: typeof CvIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/now': {
      id: '/now'
      path: '/now'
      fullPath: '/now'
      preLoaderRoute: typeof NowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing': {
      id: '/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv/': {
      id: '/cv/'
      path: '/cv'
      fullPath: '/cv/'
      preLoaderRoute: typeof CvIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv/$profile': {
      id: '/cv/$profile'
      path: '/cv/$profile'
      fullPath: '/cv/$profile'
      preLoaderRoute: typeof CvProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/writing/$slug': {
      id: '/writing/$slug'
      path: '/$slug'
      fullPath: '/writing/$slug'
      preLoaderRoute: typeof WritingSlugRouteImport
      parentRoute: typeof WritingRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface WritingRouteChildren {
  WritingSlugRoute: typeof WritingSlugRoute
}

const WritingRouteChildren: WritingRouteChildren = {
  WritingSlugRoute: WritingSlugRoute,
}

const WritingRouteWithChildren =
  WritingRoute._addFileChildren(WritingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  NowRoute: NowRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  WritingRoute: WritingRouteWithChildren,
  CvProfileRoute: CvProfileRoute,
  CvIndexRoute: CvIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
